/**
 * This file is auto-generated by the generate-components.ts script.
 * Do not edit this file directly. Instead, edit the script and run it again.
 */

import { forwardRef, Ref } from 'react';
import { useIcon } from '../hooks/use-icon';
import type { IconProps } from '../types/icons/icon-types';
import SvgIcon from '../svg/php.svg';

const Php = (originalProps: IconProps, ref: Ref<SVGSVGElement>) => {
  const { iconProps: props } = useIcon(originalProps);

  return <SvgIcon {...props} ref={ref} />;
};

export default forwardRef(Php);
