import fs from 'node:fs';
import path from 'node:path';

const SVG_DIRECTORY = './src/svg';
const OUTPUT_DIRECTORY = './src/components';
const DYNAMIC_DIRECTORY = './src/hooks';
const TYPES_DIRECTORY = './src/types/icons';

const GENERATED_COMMENT = `/**
 * This file is auto-generated by the generate-components.ts script.
 * Do not edit this file directly. Instead, edit the script and run it again.
 */
`;

function createDirectoriesIfMissing(directories: string[]) {
  for (const directory of directories) {
    if (!fs.existsSync(directory)) {
      console.log(`Creating directory: ${directory}...`);
      fs.mkdirSync(directory, { recursive: true });
    }
  }
}

type ComponentInfo = {
  fileName: string;
  componentName: string;
};

function getComponentName(fileName: string): ComponentInfo {
  const name = fileName.replace('.svg', '');
  const componentName = name.charAt(0).toUpperCase() + name.slice(1).replace(/-([a-z])/g, match => match[1].toUpperCase());
  return { fileName, componentName };
}

function getComponentInfoMap(svgFiles: string[]): ComponentInfo[] {
  const namesSet = new Set<string>();
  const componentNames = svgFiles.map(getComponentName);
  for (const { componentName } of componentNames) {
    if (namesSet.has(componentName)) {
      throw new Error(`Duplicate component name detected: ${componentName}. Please rename the SVG file to ensure unique component names.`);
    }
    namesSet.add(componentName);
  }
  return svgFiles.map(getComponentName);
}

function generateComponentFiles(componentNames: ComponentInfo[]) {
  for (const { fileName, componentName } of componentNames) {
    console.log(`Generating component for ${componentName}...`);
    const content = `${GENERATED_COMMENT}
import { forwardRef, Ref } from "react";
import { useIcon } from "../hooks/use-icon";
import type { IconProps } from "../types/icons/icon-types";
import SvgIcon from "../svg/${fileName}";

const ${componentName} = (originalProps: IconProps, ref: Ref<SVGSVGElement>) => {
  const { iconProps: props } = useIcon(originalProps);

  return <SvgIcon {...props} ref={ref} />;
};

export default forwardRef(${componentName});
`;
    fs.writeFileSync(path.join(OUTPUT_DIRECTORY, `${componentName}.tsx`), content);
  }
}

function generateIndexFile(componentNames: string[]) {
  console.log('Generating index.ts...');
  const content: string[] = [
    "export * from './types/icons/icon-names';",
    "export * from './types/icons/icon-types';",
    "export * from './hooks/use-icon';",
    "export { default as DynamicIconLoad } from './components/dynamic/DynamicIconLoad';"
  ];

  for (const component of componentNames) {
    content.push(`export { default as ${component} } from './components/${component}';`);
  };

  fs.writeFileSync('./src/index.ts', content.join('\n') + '\n');
}

function generateTypesFile(componentNames: string[]) {
  console.log('Generating icon-names.ts...');
  const content = `export type SvgIconName =
  | ${componentNames.map(name => `'${name}'`).join('\n  | ')};
`;
  fs.writeFileSync(path.join(TYPES_DIRECTORY, 'icon-names.ts'), content);
}

function generateUseIconLoadersFile(componentNames: string[]) {
  console.log('Generating use-icon-loaders.ts...');
  const content = `${GENERATED_COMMENT}
import type { ComponentType, SVGProps } from "react";
import type { SvgIconName } from "../types/icons/icon-names";

export const iconLoaders: Record<
  SvgIconName,
  () => Promise<{ default: ComponentType<SVGProps<SVGSVGElement>> }>
> = {
${componentNames.map(name => `  '${name}': () => import("../components/${name}"),`).join('\n')}
};

export function loadIcon(name: SvgIconName) {
  const loader = iconLoaders[name];
  if (!loader) {
    return Promise.reject(new Error(\`Icon not found: \${name}\`));
  }
  return loader();
}
`;
  fs.writeFileSync(path.join(DYNAMIC_DIRECTORY, 'use-icon-loaders.ts'), content);
}

async function generateComponents() {
  createDirectoriesIfMissing([
    OUTPUT_DIRECTORY,
    DYNAMIC_DIRECTORY,
    TYPES_DIRECTORY
  ]);

  const svgFiles = fs.readdirSync(SVG_DIRECTORY).filter((file: string) => file.endsWith('.svg'));
  const componentInfo = getComponentInfoMap(svgFiles);
  const componentNames = componentInfo.map(info => info.componentName);

  generateComponentFiles(componentInfo);
  generateIndexFile(componentNames);
  generateUseIconLoadersFile(componentNames);
  generateTypesFile(componentNames);

  console.log(`✅ Successfully generated ${svgFiles.length} thin wrappers, SvgIconName type, and index.ts!`);
}

generateComponents().catch((error) => {
  console.error('Failed to generate components:', error);
  process.exit(1);
});
